{
 "title": "redis-GunYu",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(redisGunYu_output_send_cmd,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "input offset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input)",
     "legendFormat": "{{input}}"
    }
   ]
  },
  {
   "title": "send cmds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(redisGunYu_output_send_cmd{cluster=\"$cluster\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "storage ratio(max)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_storage_ratio{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(sum(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - sum(redisGunYu_output_send_offset{cluster=\"$cluster\"})by(input)))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "max sync delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_output_sync_delay{cluster=\"$cluster\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "send cmds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_send_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "success cmds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_success_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fail cmds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_fail_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "filter cmds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_filter_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sender",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_sender{cluster=\"$cluster\"}[2m])) by(transaction, result)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "LAG(ack to input)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(sum(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - sum(redisGunYu_output_ack_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "LAG(ack to input)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(sum(redisGunYu_output_send_offset{cluster=\"$cluster\"}) by(input) - sum(redisGunYu_output_ack_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LAG(send to input)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(sum(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - sum(redisGunYu_output_send_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LAG(sync delay)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(redisGunYu_output_sync_delay{cluster=\"$cluster\"}) by(input) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "leader send",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_replica_leader_send{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "follower recv",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_replica_follower_recv{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage size",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redisGunYu_storage_size{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AOF write",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_aof_write{cluster=\"$cluster\"}[1m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RDB write",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_rdb_write{cluster=\"$cluster\"}[1m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Golang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{cluster=\"$cluster\"}[2m])) by(instance) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{cluster=\"$cluster\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go memstats derivs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{cluster=\"$cluster\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc avg",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{cluster=\"$cluster\"}[2m])) by (instance) /  sum(rate(go_gc_duration_seconds_count{cluster=\"$cluster\"}[2m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "goroutine",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc P75",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "\r\nsum(go_gc_duration_seconds{quantile=\"0.75\",cluster=\"$cluster\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}