{
 "title": "redis-GunYu",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(redisGunYu_output_send_cmd,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "input redis offset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input)",
     "legendFormat": "{{input}}"
    }
   ]
  },
  {
   "title": "QPS(send to output)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(redisGunYu_output_send_cmd{cluster=\"$cluster\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "storage usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_storage_ratio{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max lag(bytes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_send_offset{cluster=\"$cluster\"})by(input)))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "max lag(duration)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_output_sync_delay{cluster=\"$cluster\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "restart count(within 30m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(redisGunYu_input_sync_type{cluster=\"$cluster\"}[30m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS(commands)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_send_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QPS(success batched)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_success_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QPS(failed batched)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_fail_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QPS(filteredcommands)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_filter_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QPS(send batched)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_sender{cluster=\"$cluster\"}[2m])) by(transaction, result)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag(newest input - acked by output)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_ack_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "size(output queue)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(max(redisGunYu_output_send_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_ack_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "size(queue)",
     "type": "timeseries",
     "description": "offset of input - offset of send to output",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_send_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lag(duration)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "max(redisGunYu_output_sync_delay{cluster=\"$cluster\"}) by(input) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "restart counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(redisGunYu_input_sync_type{cluster=\"$cluster\"}) by (input)",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "restart counter  of full sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(redisGunYu_input_sync_type{cluster=\"$cluster\", sync_type=\"full\"}) by (input)",
       "legendFormat": "{{input}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "send data from leader(bytes)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_replica_leader_send{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "received data by follower(bytes)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_replica_follower_recv{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "role changed count(within 30min)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(redisGunYu_syncer_role_change{cluster=\"$cluster\"}[30m])) by (input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sync restart count(within 30min)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(redisGunYu_input_sync_type{cluster=\"$cluster\"}[30m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage usage size",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redisGunYu_storage_size{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AOF",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_aof_write{cluster=\"$cluster\"}[1m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RDB",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_rdb_write{cluster=\"$cluster\"}[1m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Golang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{cluster=\"$cluster\"}[2m])) by(instance) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{cluster=\"$cluster\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go memstats derivs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{cluster=\"$cluster\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc avg",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{cluster=\"$cluster\"}[2m])) by (instance) /  sum(rate(go_gc_duration_seconds_count{cluster=\"$cluster\"}[2m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "goroutine",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc P75",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "\r\nsum(go_gc_duration_seconds{quantile=\"0.75\",cluster=\"$cluster\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}