{
 "title": "redis-GunYu中文",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(redisGunYu_output_send_cmd,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "源偏移量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input)",
     "legendFormat": "{{input}}"
    }
   ]
  },
  {
   "title": "发送命令QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(redisGunYu_output_send_cmd{cluster=\"$cluster\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "本地缓存存储占比",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_storage_ratio{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "最大复制延迟(字节)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_send_offset{cluster=\"$cluster\"})by(input)))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "复制延迟(时间)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redisGunYu_output_sync_delay{cluster=\"$cluster\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "30分钟内同步流程启动次数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(redisGunYu_input_sync_type{cluster=\"$cluster\"}[30m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "命令",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "发送命令QPS",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_send_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "过滤命令",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_filter_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "失败命令(批量)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_fail_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "成功命令QPS(批量)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_success_cmd{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "发送命令(批量), 结果和模式",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_output_sender{cluster=\"$cluster\"}[2m])) by(transaction, result)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "同步",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "同步状态",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(redisGunYu_input_input_sync{cluster=\"$cluster\"}) by(input) ",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "延迟(刚接收到的偏移 - 已成功同步的偏移)",
     "type": "timeseries",
     "description": "已读取到的源端偏移 - 已成功写入目的端的偏移",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_ack_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "延迟(刚接收到最新的源端偏移 - 正发往目的端的偏移)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(max(redisGunYu_input_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_send_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "目的端延迟(目的端执行成功的偏移 - 正发往目的端的偏移)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "abs(max(redisGunYu_output_send_offset{cluster=\"$cluster\"}) by(input) - max(redisGunYu_output_ack_offset{cluster=\"$cluster\"})by(input))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "延迟(命令从写入源端到同步到目的端的时间间隔)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "max(redisGunYu_output_sync_delay{cluster=\"$cluster\"}) by(input) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "同步流程启动次数(5分钟内)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(redisGunYu_input_sync_type{cluster=\"$cluster\"}[5m])) by (input)",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "全量同步流程启动次数(累计)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(redisGunYu_input_sync_type{cluster=\"$cluster\", sync_type=\"full\"} ) by (input)",
       "legendFormat": "{{input}}"
      }
     ]
    },
    {
     "title": "同步工具主从切换次数(5分钟内)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(increase(redisGunYu_syncer_role_change{cluster=\"$cluster\"}[5m])) by (input)",
       "legendFormat": "{{input}}"
      }
     ]
    }
   ]
  },
  {
   "title": "集群",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "主发送字节数",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_replica_leader_send{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "从接收到的字节数",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_replica_follower_recv{cluster=\"$cluster\"}[1m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "主从角色切换次数[30分钟内]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(redisGunYu_syncer_role_change{cluster=\"$cluster\"}[30m])) by (input)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "同步流程启动次数[30分钟内]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(redisGunYu_input_sync_type{cluster=\"$cluster\"}[30m])) by(input)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "本地缓存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "存储数据量",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redisGunYu_storage_size{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AOF写入的数据",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_aof_write{cluster=\"$cluster\"}[1m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RDB写入的数据",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 11, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(redisGunYu_rdb_write{cluster=\"$cluster\"}[1m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Golang相关指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{cluster=\"$cluster\"}[2m])) by(instance) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{cluster=\"$cluster\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "go memstats derivs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{cluster=\"$cluster\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc avg",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{cluster=\"$cluster\"}[2m])) by (instance) /  sum(rate(go_gc_duration_seconds_count{cluster=\"$cluster\"}[2m])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "goroutine",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc P75",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "\r\nsum(go_gc_duration_seconds{quantile=\"0.75\",cluster=\"$cluster\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}