server:
  listen: 127.0.0.1:18000
  listenPeer: 127.0.0.1:18000
  gracefullStopTimeout: 1s
  checkRedisTypologyTicker: 10s
input:
  redis:
    addresses: [127.0.0.1:16300,127.0.0.1:16301]
    type: cluster
  mode: dynamic
  syncDelayTestKey: redis-GunYu-syncDelay-testKey
  syncFrom: prefer_slave
  # checkpoint
  syncCheckPointKey: redis-GunYu-Checkpoint-ClusterAAA
  filterCheckPointKey: redis-GunYu-Checkpoint-ClusterBBB
  # 是否跳过回放RDB文件. 默认为false。建立连接后,直接使用aof进行增量同步生成checkpoint，该参数用于配置双向同步时，忽略回放RDB文件。
  skipReplyRdb: false
  # 用于将目标段执行的命令记录到日志文件中，以便后续分析
  # 开启 curl -XPOST http://127.0.0.1:18000/syncer/print-cmd-to-target?enable=1
  # 关闭 curl -XPOST http://127.0.0.1:18000/syncer/print-cmd-to-target?enable=0
  printCmdToTarget: false
channel:
  storer:
    dirPath: /tmp/redisgunyu-cluster
    maxSize: 209715200
    logSize: 20971520
  staleCheckpointDuration: 10m
output:
  redis:
    addresses: [127.0.0.1:16400,127.0.0.1:16401]
    type: cluster
  replay:
    resumeFromBreakPoint: true
    keyExists: replace
    metric: true
    targetDb: -1
    replayTransaction: true
log:
  level: info
  handler:
    stdout: true
  withCaller: false
  withFunc: false
cluster:
  groupName: redis1
  leaseTimeout: 9s
  # metaEtcd: 
  #   endpoints:
  #     - 127.0.0.1:2379